-- Student & Client Marketplace — full schema v2 (PostgreSQL / Supabase)
--
-- Run in the Supabase SQL Editor. This REPLACES the v1 schema.
-- The DROP block clears the old tables; remove it if you have data to keep.

DROP TABLE IF EXISTS certificates, assessments, reviews, notifications,
  submissions, milestones, assignments, project_requests, engagements,
  project_applications, applications,
  project_skills, projects,
  lecturer_fields, student_skills, skills, passcodes, student_profiles,
  lecturer_profiles, companies, client_profiles, universities, fields,
  audit_log, messages, ratings, users CASCADE;

-- ---------------------------------------------------------------- accounts

CREATE TABLE users (
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fullname      VARCHAR(150) NOT NULL,
    email         VARCHAR(150) UNIQUE NOT NULL,
    password      VARCHAR(255) NOT NULL,
    role          VARCHAR(20) NOT NULL
                  CHECK (role IN ('student','lecturer','university','company','admin')),
    status        VARCHAR(20) NOT NULL DEFAULT 'active'
                  CHECK (status IN ('active','blocked')),
    blocked_reason TEXT,
    last_login_at TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_users_role ON users (role);

-- Curriculum areas. A lecturer's expertise and a project's field both point
-- here; matching the two is what decides which jobs a lecturer can see.
CREATE TABLE fields (
    id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(120) UNIQUE NOT NULL,
    faculty  VARCHAR(120)
);

CREATE TABLE universities (
    id                 INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               VARCHAR(200) UNIQUE NOT NULL,
    slug               VARCHAR(90) UNIQUE NOT NULL,
    website            VARCHAR(255),
    city               VARCHAR(120),
    contact_email      VARCHAR(150),
    admin_user_id      INT REFERENCES users(id) ON DELETE SET NULL,
    subscription_status VARCHAR(20) NOT NULL DEFAULT 'pending'
                       CHECK (subscription_status IN ('pending','active','expired','suspended')),
    subscribed_until   DATE,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE companies (
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             INT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    name                VARCHAR(200) NOT NULL,
    description         TEXT,
    website             VARCHAR(255),
    phone               VARCHAR(50),
    subscription_status VARCHAR(20) NOT NULL DEFAULT 'pending'
                        CHECK (subscription_status IN ('pending','active','expired','suspended')),
    subscribed_until    DATE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE student_profiles (
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       INT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    university_id INT REFERENCES universities(id) ON DELETE SET NULL,
    field_id      INT REFERENCES fields(id) ON DELETE SET NULL,
    department    VARCHAR(200),
    level         VARCHAR(50),
    matric_no     VARCHAR(60),
    github_url    VARCHAR(255),
    bio           TEXT,
    phone         VARCHAR(50),
    available     BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE lecturer_profiles (
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       INT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    university_id INT NOT NULL REFERENCES universities(id) ON DELETE CASCADE,
    department    VARCHAR(200),
    staff_no      VARCHAR(60),
    phone         VARCHAR(50)
);

-- A lecturer may hold expertise in several curriculum areas.
CREATE TABLE lecturer_fields (
    lecturer_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    field_id    INT NOT NULL REFERENCES fields(id) ON DELETE CASCADE,
    PRIMARY KEY (lecturer_id, field_id)
);

-- One-time codes a university issues so its lecturers can register.
CREATE TABLE passcodes (
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    university_id INT NOT NULL REFERENCES universities(id) ON DELETE CASCADE,
    code_hash     VARCHAR(255) NOT NULL,
    code_hint     VARCHAR(12) NOT NULL,
    label         VARCHAR(150),
    issued_by     INT REFERENCES users(id) ON DELETE SET NULL,
    used_by       INT REFERENCES users(id) ON DELETE SET NULL,
    used_at       TIMESTAMPTZ,
    expires_at    TIMESTAMPTZ NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_passcodes_open ON passcodes (university_id) WHERE used_at IS NULL;

-- ---------------------------------------------------------------- work

CREATE TABLE skills (
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE projects (
    id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id        INT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    field_id          INT NOT NULL REFERENCES fields(id),
    title             VARCHAR(255) NOT NULL,
    description       TEXT NOT NULL,
    deliverables      TEXT,
    difficulty        VARCHAR(20) DEFAULT 'beginner'
                      CHECK (difficulty IN ('beginner','intermediate','advanced')),
    deadline          DATE NOT NULL,
    max_students      INT NOT NULL DEFAULT 1,
    status            VARCHAR(20) NOT NULL DEFAULT 'draft'
                      CHECK (status IN ('draft','open','engaged','completed','cancelled')),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_projects_status ON projects (status);
CREATE INDEX idx_projects_field ON projects (field_id);

CREATE TABLE project_skills (
    project_id INT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    skill_id   INT NOT NULL REFERENCES skills(id) ON DELETE CASCADE,
    PRIMARY KEY (project_id, skill_id)
);

-- A lecturer asks the company for a project before placing anyone on it.
CREATE TABLE project_requests (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id  INT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    lecturer_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    message     TEXT NOT NULL,
    places      INT NOT NULL DEFAULT 1,
    status      VARCHAR(20) NOT NULL DEFAULT 'pending'
                CHECK (status IN ('pending','approved','declined','withdrawn')),
    decided_at  TIMESTAMPTZ,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (project_id, lecturer_id)
);

CREATE INDEX idx_requests_project ON project_requests (project_id);

CREATE TABLE assignments (
    id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id     INT REFERENCES project_requests(id) ON DELETE CASCADE,
    project_id     INT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    student_id     INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    lecturer_id    INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status         VARCHAR(20) NOT NULL DEFAULT 'assigned'
                   CHECK (status IN ('assigned','in_progress','submitted',
                                     'revision','approved','completed','cancelled')),
    assigned_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at   TIMESTAMPTZ,
    UNIQUE (project_id, student_id)
);

-- Fixed phases so the lecturer can watch progress against the deadline.
CREATE TABLE milestones (
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assignment_id INT NOT NULL REFERENCES assignments(id) ON DELETE CASCADE,
    phase         INT NOT NULL,
    title         VARCHAR(150) NOT NULL,
    due_date      DATE NOT NULL,
    status        VARCHAR(20) NOT NULL DEFAULT 'pending'
                  CHECK (status IN ('pending','in_progress','done')),
    note          TEXT,
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (assignment_id, phase)
);

-- Work travels student -> lecturer -> university -> company. "stage" is
-- whoever currently holds it.
CREATE TABLE submissions (
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assignment_id INT NOT NULL REFERENCES assignments(id) ON DELETE CASCADE,
    version       INT NOT NULL DEFAULT 1,
    repo_url      VARCHAR(255),
    notes         TEXT,
    stage         VARCHAR(20) NOT NULL DEFAULT 'with_lecturer'
                  CHECK (stage IN ('with_lecturer','with_university','with_company',
                                   'approved','revision')),
    submitted_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Every hand-off and every comment along the chain.
CREATE TABLE reviews (
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id INT NOT NULL REFERENCES submissions(id) ON DELETE CASCADE,
    reviewer_id   INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    reviewer_role VARCHAR(20) NOT NULL,
    action        VARCHAR(20) NOT NULL
                  CHECK (action IN ('forward','approve','request_correction')),
    comment       TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_reviews_submission ON reviews (submission_id);

-- In-app messages. Every hand-off writes one.
CREATE TABLE notifications (
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    body       TEXT NOT NULL,
    url        VARCHAR(255),
    read_at    TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_notifications_unread ON notifications (user_id) WHERE read_at IS NULL;

CREATE TABLE certificates (
    id                 INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id         INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    project_id         INT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    certificate_number VARCHAR(100) UNIQUE NOT NULL,
    issued_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Every block, unblock and subscription change is recorded.
CREATE TABLE audit_log (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id    INT REFERENCES users(id) ON DELETE SET NULL,
    action      VARCHAR(60) NOT NULL,
    target_type VARCHAR(40),
    target_id   INT,
    detail      TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------- seed

INSERT INTO fields (name, faculty) VALUES
('Software Engineering','Engineering'),
('Computer Science','Science'),
('Information Technology','Science'),
('Cybersecurity','Science'),
('Data Science','Science'),
('Artificial Intelligence','Science'),
('Electrical Engineering','Engineering'),
('Mechanical Engineering','Engineering'),
('Civil Engineering','Engineering'),
('Statistics','Science'),
('Mass Communication','Arts'),
('Business Administration','Management'),
('Accounting','Management'),
('Architecture','Environmental Sciences'),
('Biochemistry','Science')
ON CONFLICT (name) DO NOTHING;

INSERT INTO skills (name) VALUES
('Python'),('Flask'),('Django'),('JavaScript'),('React'),('Node.js'),
('MySQL'),('PostgreSQL'),('MongoDB'),('HTML'),('CSS'),('PHP'),('Java'),
('C++'),('Machine Learning'),('Data Analysis'),('UI/UX Design'),
('Figma'),('Cybersecurity'),('Networking'),('Technical Writing'),
('Digital Marketing'),('Android'),('Flutter'),('Git'),('AutoCAD'),('MATLAB')
ON CONFLICT (name) DO NOTHING;
